# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='version_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.SmallIntegerField(default=0)),
                ('compulsory_update', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
